name: Justin Pardee
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37128
title: Justin Pardee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffff8'
    - '#352829'
    - '#a7ab96'
    - '#43558c'
    - '#707261'
  brandStrength: 0.3125
  lightness: 0.12369499518536031
  saturation: 0.27571350359357893
  rhythmicContrast: 0.10268628806807101
purpose: []
