name: Justin Pardee
favicon: null
layout_spectrum: 0.14964279532432556
typography_spectrum: 0.3619267628528178
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffbfa'
    - '#193328'
    - '#cbc7ac'
    - '#5f8ca3'
    - '#cd9578'
  brandStrength: 0.3125
  lightness: 0.12369499518536031
  saturation: 0.27571350359357893
  rhythmicContrast: 0.10268628806807101
purpose: []
